apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "openmct-ingress"
  labels:
    app: openmct-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - path: /hello-cisco(/|$)(.*)
        backend:
          serviceName: "openmct"
          servicePort: 8080
